name: Automate Database Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MySQL client and jq
        run: sudo apt-get update && sudo apt-get install -y mysql-client jq

      - name: Replace password placeholder in SQL script
        run: sed -i "s/@@AUTO_USER_PASSWORD@@/${{ secrets.AUTO_USER_PASSWORD }}/g" init.sql

      - name: Run SQL script
        env:
          MYSQL_PWD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: mysql -h 127.0.0.1 -u root < init.sql

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Configure ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Expose MySQL via ngrok
        run: ngrok tcp 3306 --log=stdout > ngrok.log &

      - name: Get ngrok URL
        run: |
          sleep 10
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Ngrok URL: $NGROK_URL"

      - name: Keep tunnel open (optional)
        run: sleep 300
