name: Automate Database Creation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-database:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrong@Passw0rd
          MSSQL_PID: Express
        ports:
          - 1433:1433
        options: --health-cmd "opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SQL Server Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Setup ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok authtoken $NGROK_AUTH_TOKEN
          ngrok tcp 1433 &

      - name: Wait for SQL Server and ngrok
        run: |
          sleep 20 # Wait for SQL Server and ngrok to start
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Ngrok URL: $NGROK_URL"
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

      - name: Create Database and Table
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q "CREATE DATABASE AutoTest;"
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -d AutoTest -Q "CREATE TABLE [user] (Name VARCHAR(50), Surname VARCHAR(50), Email VARCHAR(100));"

      - name: Create Stored Procedure and User
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -d AutoTest -Q "
            CREATE PROCEDURE CreateAutoUser
            AS
            BEGIN
              CREATE LOGIN Auto_user WITH PASSWORD = 'AutoUser@Passw0rd';
              CREATE USER Auto_user FOR LOGIN Auto_user;
              ALTER ROLE db_owner ADD MEMBER Auto_user;
            END;
            EXEC CreateAutoUser;"
          
      - name: Insert Sample Data
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -d AutoTest -Q "INSERT INTO [user] (Name, Surname, Email) VALUES ('John', 'Doe', 'john.doe@example.com');"

      - name: Verify Data
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -d AutoTest -Q "SELECT * FROM [user];"
