name: Setup SQL Server Database

on: [push]

jobs:
  setup-db:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLCMD
        run: |
          choco install sqlserver-cmdlineutils -y
          
      - name: Verify secrets exist (safe check)
        shell: pwsh
        run: |
          if (-not "${{ secrets.SQL_SERVER }}") { Write-Error "SQL_SERVER secret is empty" }
          if (-not "${{ secrets.SQL_USER }}") { Write-Error "SQL_USER secret is empty" }
          Write-Output "Secrets appear to be set (values hidden for security)"
          
      - name: Run SQL Script
        shell: pwsh
        run: |
          $server = "${{ secrets.SQL_SERVER }}"
          $user = "${{ secrets.SQL_USER }}"
          $pass = "${{ secrets.SQL_PASSWORD }}"
          
          Write-Output "Attempting connection to server (name hidden for security)..."
          sqlcmd -S $server -U $user -P $pass -i setup.sql
