name: Setup SQL Server Database

on: [push]

jobs:
  setup-db:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLCMD
        run: |
          choco install sqlserver-cmdlineutils -y
          
      - name: Verify secrets are accessible
        run: |
          Write-Output "SQL_SERVER secret exists: $(${{ secrets.SQL_SERVER }} -ne '')"
          Write-Output "SQL_USER secret exists: $(${{ secrets.SQL_USER }} -ne '')"
          
      - name: Run SQL Script
        run: |
          sqlcmd -S "${{ secrets.SQL_SERVER }}" -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i setup.sql
