name: Setup SQL Server Database

on: [push]

jobs:
  setup-db:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLCMD
        run: |
          choco install sqlserver-cmdlineutils -y
      - name: Debug print variables
        run: |
          echo "SQL_SERVER: ${{ secrets.SQL_SERVER }}"
          echo "SQL_USER: ${{ secrets.SQL_USER }}"
          # Mask password for security
          echo "SQL_PASSWORD: ***"

      - name: Run SQL Script
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -i setup.sql
